### ISSUE TITLE
improvement: replace scrollEnabled react state implementation with useAnimatedProps from reanimated

### ISSUE THREAD

**Issue by intergalacticspacehighway** [intergalacticspacehighway/react-native-reanimated-zoom#10]
[Here](https://github.com/intergalacticspacehighway/react-native-reanimated-zoom/blob/main/src/createZoomListComponent.tsx#L7) we're using `scrollEnabled` with react state to disable scrollview's scroll if zoom is enabled. We can replace this implementation with [useAnimatedProps](https://docs.swmansion.com/react-native-reanimated/docs/api/hooks/useAnimatedProps/) from reanimated to improve the performance.

However, this will require us to use  Animated.createdAnimatedComponent from reanimated. We also need to think what happens if the user passes an Animated ScrollView/FlatList.

**Comment by itzhak-ira** [comment]
Any potential performance boost that mitigates the need to use state should 100% be considered. You can set an optional prop to utilize this feature (maybe `initWithAnimatedCompoment`?) which warns that this prop will negate ability to pass in their own animated component.

I’m looking to implement this lib for a large client pretty soon, do you think you can add this feature as simply an experimental addition (to start) soon?

**Comment by intergalacticspacehighway** [comment]
@itzhak-ira resolved with https://github.com/intergalacticspacehighway/react-native-reanimated-zoom/pull/12. Let me know if it works for you. Thanks for the suggestion!
